name: flutter_bluetooth_serial_example
version: 0.2.2
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors: 
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  firebase_auth: ^0.15.1
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^3.2.4
  shared_preferences: ^0.4.3
  fluttertoast: ^3.1.3
  firebase_database: ^3.0.7
  intl: ^0.15.8
  flutter_speed_dial: ^1.2.4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - img/bg.jpg
    - img/bg1.png
    - img/btn_login.png
    - img/logo.png
    - img/drawer.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf